const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  getState: () => ipcRenderer.invoke('app:get-state'),
  pingServers: () => ipcRenderer.invoke('servers:ping'),
  loginDiscord: () => ipcRenderer.invoke('auth:discord'),
  logout: () => ipcRenderer.invoke('auth:logout'),
  cancelLogin: () => ipcRenderer.invoke('auth:cancel'),
  setUsername: (name) => ipcRenderer.invoke('profile:set-username', name),
  play: (serverId) => ipcRenderer.invoke('game:play', serverId),
  openGameFolder: () => ipcRenderer.invoke('game:open-folder'),
  repairInstall: () => ipcRenderer.invoke('game:repair'),
  openInvite: () => ipcRenderer.invoke('app:open-invite'),
  getSettings: () => ipcRenderer.invoke('settings:get'),
  saveSettings: (partial) => ipcRenderer.invoke('settings:save', partial),
  resetSettings: () => ipcRenderer.invoke('settings:reset'),
  pickJava: () => ipcRenderer.invoke('settings:pick-java'),
  minimize: () => ipcRenderer.send('win:minimize'),
  close: () => ipcRenderer.send('win:close'),
  onProgress: (cb) => ipcRenderer.on('progress', (_e, data) => cb(data)),
  onLog: (cb) => ipcRenderer.on('log', (_e, line) => cb(line)),
  copyCrashLog: () => ipcRenderer.invoke('crash:copy-log'),
  openCrashReport: () => ipcRenderer.invoke('crash:open-report'),
  copyText: (text) => ipcRenderer.invoke('app:copy-text', text),
  setSkin: (name) => ipcRenderer.invoke('skin:set', name),
  tourDone: () => ipcRenderer.invoke('tour:done'),
  onCrash: (cb) => ipcRenderer.on('game-crash', (_e, data) => cb(data)),
  onPlaytime: (cb) => ipcRenderer.on('playtime', (_e, data) => cb(data)),
  installUpdate: () => ipcRenderer.invoke('update:install'),
  retryUpdate: () => ipcRenderer.invoke('update:retry'),
  getInstallStatus: () => ipcRenderer.invoke('servers:install-status'),
  getWhatsNew: () => ipcRenderer.invoke('whatsnew:get'),
  whatsNewSeen: () => ipcRenderer.invoke('whatsnew:seen'),
  onUpdate: (cb) => ipcRenderer.on('update-state', (_e, data) => cb(data)),
  onPlayState: (cb) => ipcRenderer.on('play-state', (_e, data) => cb(data))
});
